In [1]:
# importing libraries
import numpy as np
import pandas as pd

In [2]:
# reading cafe sales data
df = pd.read_csv('/workspaces/data_cleaning_project/data/raw/Cafe Sales.csv')

In [3]:
# inspecting first 10 records
df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

In [4]:
# checking for basic structure and data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [6]:
# checking if there are any duplicate records or not
print(f'cafe sales data contains {sum(df.duplicated())} duplicate records.')

cafe sales data contains 0 duplicate records.

In [7]:
# inspecting missing data for each column
df.isna().sum() * 100 / df.shape[0]

Transaction ID       0.00
Item                 3.33
Quantity             1.38
Price Per Unit       1.79
Total Spent          1.73
Payment Method      25.79
Location            32.65
Transaction Date     1.59
dtype: float64

In [13]:
# inspecting unique values in all coumns except 'Tranaction ID'
df_cols = set(df.columns)
exclude = {'Transaction ID'}
df_cols = df_cols.difference(exclude)
df_cols = list(df_cols)

for col in df_cols:
    print(f'{col}:\n{df[col].unique()}', end = '\n\n')

Price Per Unit:
<StringArray>
['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan, 'ERROR', 'UNKNOWN']
Length: 9, dtype: str

Payment Method:
<StringArray>
['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan]
Length: 6, dtype: str

Location:
<StringArray>
['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR']
Length: 5, dtype: str

Transaction Date:
<StringArray>
['2023-09-08', '2023-05-16', '2023-07-19', '2023-04-27', '2023-06-11',
 '2023-03-31', '2023-10-06', '2023-10-28', '2023-07-28', '2023-12-31',
 ...
 '2023-08-01', '2023-01-20', '2023-11-11', '2023-02-13', '2023-07-30',
 '2023-02-17', '2023-05-20', '2023-11-05', '2023-03-27', '2023-07-03']
Length: 368, dtype: str

Item:
<StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',  'UNKNOWN',
 'Sandwich',        nan,    'ERROR',    'Juice',      'Tea']
Length: 11, dtype: str

Quantity:
<StringArray>
['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', nan]
Length: 8, dtype: str

Total Spent:
<StringArray>
[    '4.0',    '12.0',   'ERROR',    '10.0',    '20.0',     '9.0',    '16.0',
    '15.0',    '25.0',     '8.0',     '5.0',     '3.0',     '6.0',       nan,
 'UNKNOWN',     '2.0',     '1.0',     '7.5',     '4.5',     '1.5']
Length: 20, dtype: str

In [16]:
# replacing ERROR and UNKNOWN values with NaN
df = df.replace(['ERROR', 'UNKNOWN'], np.nan)

df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,NaN,3,3.0,9.0,NaN,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,NaN,2023-10-28
8,TXN_4717867,NaN,5,NaN,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

In [17]:
# changing data types
df['Quantity'] = df['Quantity'].astype('Int64')
df[['Price Per Unit', 'Total Spent']] = df[['Price Per Unit', 'Total Spent']].astype('float')
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])

In [12]:
# rechecking missing data after data treatment
df.isna().sum() * 100 / df.shape[0]

Transaction ID       0.00
Item                 9.69
Quantity             4.79
Price Per Unit       5.33
Total Spent          5.02
Payment Method      31.78
Location            39.61
Transaction Date     4.60
dtype: float64

In [13]:
# dropping records where Transaction Date is missing
df = df.dropna(subset = ['Transaction Date'])

In [16]:
# replacing missing values in Payment Method and Location with INA (Information Nor Available)
# dropping these high volume arecords would lead to significant data loss
# imputing INA avoids bias
df[['Payment Method', 'Location']] = df[['Payment Method', 'Location']].fillna('INA')

In [17]:
# inspecting mean and median values for Quantity
quantity_mean, quantity_median = round(df['Quantity'].mean(),0), round(df['Quantity'].median(),0)

print(f'Mean Quantity: {quantity_mean}\nMedian Quantity: {quantity_median}')

Mean Quantity: 3.0
Median Quantity: 3.0

In [18]:
# since mean and median values Are similar, replacing missing values in Quantity with mean value
df['Quantity'] = df['Quantity'].fillna(quantity_mean)

In [19]:
# replacing missing values in Item with mode value
df['Item'] = df['Item'].fillna(df['Item'].mode()[0])

In [6]:
# checking how many distinct prices exist for each Item category and how many times each price point is registered.
df.groupby('Item')['Price Per Unit'].value_counts()

Item      Price Per Unit
Cake      3.0               1085
          ERROR               19
          UNKNOWN             14
Coffee    2.0               1108
          UNKNOWN             20
          ERROR               18
Cookie    1.0               1026
          ERROR               21
          UNKNOWN             21
ERROR     3.0                 77
          4.0                 61
          5.0                 39
          1.5                 37
          1.0                 34
          2.0                 31
          ERROR                3
          UNKNOWN              3
Juice     3.0               1110
          ERROR               26
          UNKNOWN             18
Salad     5.0               1082
          ERROR               34
          UNKNOWN             16
Sandwich  4.0               1082
          UNKNOWN             19
          ERROR               13
Smoothie  4.0               1036
          ERROR               19
          UNKNOWN             17
Tea       1.5               1023
          ERROR               25
          UNKNOWN             21
UNKNOWN   3.0                 77
          4.0                 70
          2.0                 49
          5.0                 45
          1.0                 45
          1.5                 40
          UNKNOWN              7
          ERROR                4
Name: count, dtype: int64

In [9]:
# filling missing price per unit values with the most frequent (mode) price for each item category
df['Price Per Unit'] =  df.groupby('Item')['Price Per Unit'].transform(lambda x: x.fillna(x.mode()[0]))

In [18]:
# filling missing records for total spent by calculating the product of quantity times price per unit
df['Total Spent'] = df['Total Spent'].fillna(df['Quantity'] * df['Price Per Unit'])

In [4]:
# storing clean data
df.to_csv('/workspaces/data_cleaning_project/data/raw/Cafe Sales.csv', index = False)

In [15]:
df.isna().sum() * 100 / df.shape[0]

Transaction ID       0.000000
Item                 9.716981
Quantity             4.758910
Price Per Unit       5.303983
Total Spent          4.989518
Payment Method      31.603774
Location            39.612159
Transaction Date     0.000000
dtype: float64

In [14]:
df.info()

<class 'pandas.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   str
 1   Item              8613 non-null   str
 2   Quantity          9086 non-null   Int64
 3   Price Per Unit    9034 non-null   float64
 4   Total Spent       9064 non-null   float64
 5   Payment Method    6525 non-null   str
 6   Location          5761 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(2), str(4)
memory usage: 680.1 KB